#cloud-config
users:
  - name: ${username}
    groups: sudo
    shell: /bin/bash
    sudo: ['ALL=(ALL) NOPASSWD:ALL']
    ssh_authorized_keys:
      - ${ssh_key}
package_update: true
package_upgrade: false
packages:
 - vim
 - nginx
runcmd:
 - ufw allow 22
 - echo "y" | ufw enable
